name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.16.0] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

    
      - name: Asenna backend-riippuvuudet
        working-directory: ./backend
        run: npm install

      - name: Asenna frontend-riippuvuudet
        working-directory: ./frontend
        run: npm install

    
      - name: Suorita backend-testit
        working-directory: ./backend
        run: npm test

      - name: Suorita frontend-testit
        working-directory: ./frontend
        run: npm test

    
      - name: Linttaa backend
        working-directory: ./backend
        run: npm run lint

      - name: Linttaa frontend
        working-directory: ./frontend
        run: npm run lint
